Fix retry.

diff --git a/.github/workflows/_build.yml b/.github/workflows/_build.yml
--- a/.github/workflows/_build.yml
+++ b/.github/workflows/_build.yml
@@ -41,7 +41,6 @@ jobs:
   build-wheel:
     runs-on: ${{ inputs.runs-on }}
     name: Build wheel (${{ inputs.release-version }}-${{ inputs.python-version }}-${{ inputs.cuda-version }}-${{ inputs.torch-version }}-${{ inputs.cxx11_abi }})
-    retries: 3
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -142,40 +141,45 @@ jobs:
 
       - name: Build wheel
         id: build_wheel
-        run: |
-          # We want setuptools >= 49.6.0 otherwise we can't compile the extension if system CUDA version is 11.7 and pytorch cuda version is 11.6
-          # https://github.com/pytorch/pytorch/blob/664058fa83f1d8eede5d66418abff6e20bd76ca8/torch/utils/cpp_extension.py#L810
-          # However this still fails so I'm using a newer version of setuptools
-          pip install setuptools==75.8.0
-          pip install ninja packaging wheel
-          export PATH=/usr/local/nvidia/bin:/usr/local/nvidia/lib64:$PATH
-          export LD_LIBRARY_PATH=/usr/local/nvidia/lib64:/usr/local/cuda/lib64:$LD_LIBRARY_PATH
-          # Limit MAX_JOBS otherwise the github runner goes OOM
-          # nvcc 11.8 can compile with 2 jobs, but nvcc 12.3 goes OOM
+        uses: Instrument-Specialist/retry-step@v1
+        with:
+          retries: 3
+          command: bash -c "$BUILD_SCRIPT"
+        env:
+          BUILD_SCRIPT: |
+            # We want setuptools >= 49.6.0 otherwise we can't compile the extension if system CUDA version is 11.7 and pytorch cuda version is 11.6
+            # https://github.com/pytorch/pytorch/blob/664058fa83f1d8eede5d66418abff6e20bd76ca8/torch/utils/cpp_extension.py#L810
+            # However this still fails so I'm using a newer version of setuptools
+            pip install setuptools==75.8.0
+            pip install ninja packaging wheel
+            export PATH=/usr/local/nvidia/bin:/usr/local/nvidia/lib64:$PATH
+            export LD_LIBRARY_PATH=/usr/local/nvidia/lib64:/usr/local/cuda/lib64:$LD_LIBRARY_PATH
+            # Limit MAX_JOBS otherwise the github runner goes OOM
+            # nvcc 11.8 can compile with 2 jobs, but nvcc 12.3 goes OOM
 
-          export MAX_JOBS=8
-          export NVCC_THREADS=8
-          export FLASH_ATTENTION_FORCE_BUILD="TRUE"
-          export FLASH_ATTENTION_FORCE_CXX11_ABI=${{ inputs.cxx11_abi }}
+            export MAX_JOBS=8
+            export NVCC_THREADS=8
+            export FLASH_ATTENTION_FORCE_BUILD="TRUE"
+            export FLASH_ATTENTION_FORCE_CXX11_ABI=${{ inputs.cxx11_abi }}
 
-          BUILD_COMMAND="python setup.py bdist_wheel --dist-dir=dist ${{ startsWith(runner.arch, 'ARM') && '--verbose' || '' }}" 
+            BUILD_COMMAND="python setup.py bdist_wheel --dist-dir=dist ${{ startsWith(runner.arch, 'ARM') && '--verbose' || '' }}" 
 
-          # 5h timeout since GH allows max 6h and we want some buffer
-          EXIT_CODE=0
-          timeout 5h ${BUILD_COMMAND} || EXIT_CODE=$?
+            # 5h timeout since GH allows max 6h and we want some buffer
+            EXIT_CODE=0
+            timeout 5h ${BUILD_COMMAND} || EXIT_CODE=$?
 
-          if [ $EXIT_CODE -eq 0 ]; then
-            tmpname=cu${WHEEL_CUDA_VERSION}torch${MATRIX_TORCH_VERSION}cxx11abi${{ inputs.cxx11_abi }}
-            wheel_name=$(ls dist/*whl | xargs -n 1 basename | sed "s/-/+$tmpname-/2")
-            ls dist/*whl |xargs -I {} mv {} dist/${wheel_name}
-            echo "wheel_name=${wheel_name}" >> $GITHUB_ENV
-          fi
+            if [ $EXIT_CODE -eq 0 ]; then
+              tmpname=cu${WHEEL_CUDA_VERSION}torch${MATRIX_TORCH_VERSION}cxx11abi${{ inputs.cxx11_abi }}
+              wheel_name=$(ls dist/*whl | xargs -n 1 basename | sed "s/-/+$tmpname-/2")
+              ls dist/*whl |xargs -I {} mv {} dist/${wheel_name}
+              echo "wheel_name=${wheel_name}" >> $GITHUB_ENV
+            fi
 
-          # Store exit code in GitHub env for later steps
-          echo "build_exit_code=$EXIT_CODE" | tee -a "$GITHUB_OUTPUT"
+            # Store exit code in GitHub env for later steps
+            echo "build_exit_code=$EXIT_CODE" | tee -a "$GITHUB_OUTPUT"
 
-          # Do not fail the job if timeout killed the build
-          exit $EXIT_CODE
+            # Do not fail the job if timeout killed the build
+            exit $EXIT_CODE
 
       - name: Log build logs after timeout
         if: always() && steps.build_wheel.outputs.build_exit_code == 124
